// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package socialmodels

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	friendRequestsFieldNames          = builder.RawFieldNames(&FriendRequests{})
	friendRequestsRows                = strings.Join(friendRequestsFieldNames, ",")
	friendRequestsRowsExpectAutoSet   = strings.Join(stringx.Remove(friendRequestsFieldNames, "`id`", "`create_at`", "`created_at`", "`update_at`", "`updated_at`"), ",")
	friendRequestsRowsWithPlaceHolder = strings.Join(stringx.Remove(friendRequestsFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheFriendRequestsIdPrefix = "cache:goapp:friendRequests:id:"
)

type (
	friendRequestsModel interface {
		Trans(ctx context.Context, fn func(ctx context.Context,
			session sqlx.Session) error) error
		Insert(ctx context.Context, data *FriendRequests) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*FriendRequests, error)
		FindByReqUidAndUserId(ctx context.Context, rid, uid uint64) (*FriendRequests, error)
		ListNoHandler(ctx context.Context, userId uint64) ([]*FriendRequests, error)
		Update(ctx context.Context, session sqlx.Session, data *FriendRequests) error
		Delete(ctx context.Context, id int64) error
	}

	defaultFriendRequestsModel struct {
		sqlc.CachedConn
		table string
	}

	FriendRequests struct {
		Id           uint64         `db:"id"`            // 好友请求ID
		UserId       uint64         `db:"user_id"`       // 发起用户ID
		ReqUserId    uint64         `db:"req_user_id"`   // 接收请求的用户ID
		ReqMsg       sql.NullString `db:"req_msg"`       // 请求消息
		ReqTime      time.Time      `db:"req_time"`      // 请求时间
		HandleResult sql.NullInt64  `db:"handle_result"` // 处理结果: 0-拒绝, 1-接受, 2-忽略
		HandleMsg    sql.NullString `db:"handle_msg"`    // 处理消息
		HandleTime   sql.NullTime   `db:"handle_time"`   // 处理时间
		CreateTime   time.Time      `db:"create_time"`   // 创建时间
		UpdateTime   time.Time      `db:"update_time"`   // 更新时间
		DeleteTime   sql.NullTime   `db:"delete_time"`   // 删除时间
		DelState     int64          `db:"del_state"`     // 删除状态: 0-正常, 1-已删除
	}
)

func newFriendRequestsModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFriendRequestsModel {
	return &defaultFriendRequestsModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`friend_requests`",
	}
}

func (m *defaultFriendRequestsModel) Trans(ctx context.Context, fn func(ctx context.Context,
	session sqlx.Session) error) error {
	return m.TransactCtx(ctx, func(ctx context.Context, session sqlx.Session) error {
		return fn(ctx, session)
	})
}

func (m *defaultFriendRequestsModel) Delete(ctx context.Context, id int64) error {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, friendRequestsIdKey)
	return err
}

func (m *defaultFriendRequestsModel) FindOne(ctx context.Context, id int64) (*FriendRequests, error) {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, id)
	var resp FriendRequests
	err := m.QueryRowCtx(ctx, &resp, friendRequestsIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRequestsRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendRequestsModel) FindByReqUidAndUserId(ctx context.Context, rid, uid uint64) (*FriendRequests, error) {
	query := fmt.Sprintf("select %s from %s where `req_user_id` = ? and `user_id` = ?", friendRequestsRows, m.table)

	var resp FriendRequests
	err := m.QueryRowNoCacheCtx(ctx, &resp, query, rid, uid)

	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFriendRequestsModel) ListNoHandler(ctx context.Context, userId uint64) ([]*FriendRequests, error) {
	query := fmt.Sprintf("select %s from %s where `handle_result` = 1 and `req_user_id` = ?", friendRequestsRows, m.table)
	var resp []*FriendRequests
	err := m.QueryRowsNoCacheCtx(ctx, &resp, query, userId)

	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultFriendRequestsModel) Insert(ctx context.Context, data *FriendRequests) (sql.Result, error) {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (`user_id`, `req_user_id`, `req_msg`, `req_time`, `handle_result`, `handle_msg`, `handle_time`, `delete_time`, `del_state`) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table)
		return conn.ExecCtx(ctx, query, data.UserId, data.ReqUserId, data.ReqMsg, data.ReqTime, data.HandleResult, 
			data.HandleMsg, data.HandleTime, data.DeleteTime, data.DelState)
	}, friendRequestsIdKey)
	return ret, err
}

func (m *defaultFriendRequestsModel) Update(ctx context.Context, session sqlx.Session, data *FriendRequests) error {
	friendRequestsIdKey := fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, friendRequestsRowsWithPlaceHolder)
		return session.ExecCtx(ctx, query, data.UserId, data.ReqUserId, data.ReqMsg, data.ReqTime, data.HandleResult, 
			data.HandleMsg, data.HandleTime, data.DeleteTime, data.DelState, data.Id)
	}, friendRequestsIdKey)
	return err
}

func (m *defaultFriendRequestsModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheFriendRequestsIdPrefix, primary)
}

func (m *defaultFriendRequestsModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", friendRequestsRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFriendRequestsModel) tableName() string {
	return m.table
}
