// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: search.proto

package searchservice

import (
	"context"

	"github.com/liumkssq/goapp/app/search/rpc/search"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ArticleSearchResult          = search.ArticleSearchResult
	ClearSearchHistoryRequest    = search.ClearSearchHistoryRequest
	ClearSearchHistoryResponse   = search.ClearSearchHistoryResponse
	GetHotSearchKeywordsRequest  = search.GetHotSearchKeywordsRequest
	GetHotSearchKeywordsResponse = search.GetHotSearchKeywordsResponse
	GetSearchHistoryRequest      = search.GetSearchHistoryRequest
	GetSearchHistoryResponse     = search.GetSearchHistoryResponse
	GlobalSearchRequest          = search.GlobalSearchRequest
	GlobalSearchResponse         = search.GlobalSearchResponse
	HotKeyword                   = search.HotKeyword
	LostFoundSearchResult        = search.LostFoundSearchResult
	ProductSearchResult          = search.ProductSearchResult
	SearchArticlesRequest        = search.SearchArticlesRequest
	SearchArticlesResponse       = search.SearchArticlesResponse
	SearchHistoryItem            = search.SearchHistoryItem
	SearchLostFoundRequest       = search.SearchLostFoundRequest
	SearchLostFoundResponse      = search.SearchLostFoundResponse
	SearchProductsRequest        = search.SearchProductsRequest
	SearchProductsResponse       = search.SearchProductsResponse
	SearchResult                 = search.SearchResult
	SearchUsersRequest           = search.SearchUsersRequest
	SearchUsersResponse          = search.SearchUsersResponse
	UserSearchResult             = search.UserSearchResult

	SearchService interface {
		// 全局搜索
		GlobalSearch(ctx context.Context, in *GlobalSearchRequest, opts ...grpc.CallOption) (*GlobalSearchResponse, error)
		// 搜索商品
		SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error)
		// 搜索文章
		SearchArticles(ctx context.Context, in *SearchArticlesRequest, opts ...grpc.CallOption) (*SearchArticlesResponse, error)
		// 搜索失物招领
		SearchLostFound(ctx context.Context, in *SearchLostFoundRequest, opts ...grpc.CallOption) (*SearchLostFoundResponse, error)
		// 搜索用户
		SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error)
		// 获取搜索历史
		GetSearchHistory(ctx context.Context, in *GetSearchHistoryRequest, opts ...grpc.CallOption) (*GetSearchHistoryResponse, error)
		// 清除搜索历史
		ClearSearchHistory(ctx context.Context, in *ClearSearchHistoryRequest, opts ...grpc.CallOption) (*ClearSearchHistoryResponse, error)
		// 获取热门搜索关键词
		GetHotSearchKeywords(ctx context.Context, in *GetHotSearchKeywordsRequest, opts ...grpc.CallOption) (*GetHotSearchKeywordsResponse, error)
	}

	defaultSearchService struct {
		cli zrpc.Client
	}
)

func NewSearchService(cli zrpc.Client) SearchService {
	return &defaultSearchService{
		cli: cli,
	}
}

// 全局搜索
func (m *defaultSearchService) GlobalSearch(ctx context.Context, in *GlobalSearchRequest, opts ...grpc.CallOption) (*GlobalSearchResponse, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.GlobalSearch(ctx, in, opts...)
}

// 搜索商品
func (m *defaultSearchService) SearchProducts(ctx context.Context, in *SearchProductsRequest, opts ...grpc.CallOption) (*SearchProductsResponse, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.SearchProducts(ctx, in, opts...)
}

// 搜索文章
func (m *defaultSearchService) SearchArticles(ctx context.Context, in *SearchArticlesRequest, opts ...grpc.CallOption) (*SearchArticlesResponse, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.SearchArticles(ctx, in, opts...)
}

// 搜索失物招领
func (m *defaultSearchService) SearchLostFound(ctx context.Context, in *SearchLostFoundRequest, opts ...grpc.CallOption) (*SearchLostFoundResponse, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.SearchLostFound(ctx, in, opts...)
}

// 搜索用户
func (m *defaultSearchService) SearchUsers(ctx context.Context, in *SearchUsersRequest, opts ...grpc.CallOption) (*SearchUsersResponse, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.SearchUsers(ctx, in, opts...)
}

// 获取搜索历史
func (m *defaultSearchService) GetSearchHistory(ctx context.Context, in *GetSearchHistoryRequest, opts ...grpc.CallOption) (*GetSearchHistoryResponse, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.GetSearchHistory(ctx, in, opts...)
}

// 清除搜索历史
func (m *defaultSearchService) ClearSearchHistory(ctx context.Context, in *ClearSearchHistoryRequest, opts ...grpc.CallOption) (*ClearSearchHistoryResponse, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.ClearSearchHistory(ctx, in, opts...)
}

// 获取热门搜索关键词
func (m *defaultSearchService) GetHotSearchKeywords(ctx context.Context, in *GetHotSearchKeywordsRequest, opts ...grpc.CallOption) (*GetHotSearchKeywordsResponse, error) {
	client := search.NewSearchServiceClient(m.cli.Conn())
	return client.GetHotSearchKeywords(ctx, in, opts...)
}
