// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1
// Source: lostfound.proto

package lostfoundservice

import (
	"context"

	"github.com/liumkssq/goapp/app/lostfound/rpc/lostfound"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Comment                       = lostfound.Comment
	CommentLostFoundRequest       = lostfound.CommentLostFoundRequest
	CommentLostFoundResponse      = lostfound.CommentLostFoundResponse
	DeleteLostFoundRequest        = lostfound.DeleteLostFoundRequest
	DeleteLostFoundResponse       = lostfound.DeleteLostFoundResponse
	GetLostFoundCommentsRequest   = lostfound.GetLostFoundCommentsRequest
	GetLostFoundCommentsResponse  = lostfound.GetLostFoundCommentsResponse
	GetLostFoundDetailRequest     = lostfound.GetLostFoundDetailRequest
	GetLostFoundDetailResponse    = lostfound.GetLostFoundDetailResponse
	GetLostFoundListRequest       = lostfound.GetLostFoundListRequest
	GetLostFoundListResponse      = lostfound.GetLostFoundListResponse
	GetUserLostFoundRequest       = lostfound.GetUserLostFoundRequest
	GetUserLostFoundResponse      = lostfound.GetUserLostFoundResponse
	LikeLostFoundRequest          = lostfound.LikeLostFoundRequest
	LikeLostFoundResponse         = lostfound.LikeLostFoundResponse
	LostFoundItem                 = lostfound.LostFoundItem
	PublishLostFoundRequest       = lostfound.PublishLostFoundRequest
	PublishLostFoundResponse      = lostfound.PublishLostFoundResponse
	UnlikeLostFoundRequest        = lostfound.UnlikeLostFoundRequest
	UnlikeLostFoundResponse       = lostfound.UnlikeLostFoundResponse
	UpdateLostFoundRequest        = lostfound.UpdateLostFoundRequest
	UpdateLostFoundResponse       = lostfound.UpdateLostFoundResponse
	UpdateLostFoundStatusRequest  = lostfound.UpdateLostFoundStatusRequest
	UpdateLostFoundStatusResponse = lostfound.UpdateLostFoundStatusResponse

	LostFoundService interface {
		// 获取失物招领列表
		GetLostFoundList(ctx context.Context, in *GetLostFoundListRequest, opts ...grpc.CallOption) (*GetLostFoundListResponse, error)
		// 获取失物招领详情
		GetLostFoundDetail(ctx context.Context, in *GetLostFoundDetailRequest, opts ...grpc.CallOption) (*GetLostFoundDetailResponse, error)
		// 获取用户发布的失物招领
		GetUserLostFound(ctx context.Context, in *GetUserLostFoundRequest, opts ...grpc.CallOption) (*GetUserLostFoundResponse, error)
		// 发布失物招领
		PublishLostFound(ctx context.Context, in *PublishLostFoundRequest, opts ...grpc.CallOption) (*PublishLostFoundResponse, error)
		// 更新失物招领
		UpdateLostFound(ctx context.Context, in *UpdateLostFoundRequest, opts ...grpc.CallOption) (*UpdateLostFoundResponse, error)
		// 删除失物招领
		DeleteLostFound(ctx context.Context, in *DeleteLostFoundRequest, opts ...grpc.CallOption) (*DeleteLostFoundResponse, error)
		// 更新失物招领状态
		UpdateLostFoundStatus(ctx context.Context, in *UpdateLostFoundStatusRequest, opts ...grpc.CallOption) (*UpdateLostFoundStatusResponse, error)
		// 评论失物招领
		CommentLostFound(ctx context.Context, in *CommentLostFoundRequest, opts ...grpc.CallOption) (*CommentLostFoundResponse, error)
		// 获取失物招领评论
		GetLostFoundComments(ctx context.Context, in *GetLostFoundCommentsRequest, opts ...grpc.CallOption) (*GetLostFoundCommentsResponse, error)
		// 点赞失物招领
		LikeLostFound(ctx context.Context, in *LikeLostFoundRequest, opts ...grpc.CallOption) (*LikeLostFoundResponse, error)
		// 取消点赞失物招领
		UnlikeLostFound(ctx context.Context, in *UnlikeLostFoundRequest, opts ...grpc.CallOption) (*UnlikeLostFoundResponse, error)
	}

	defaultLostFoundService struct {
		cli zrpc.Client
	}
)

func NewLostFoundService(cli zrpc.Client) LostFoundService {
	return &defaultLostFoundService{
		cli: cli,
	}
}

// 获取失物招领列表
func (m *defaultLostFoundService) GetLostFoundList(ctx context.Context, in *GetLostFoundListRequest, opts ...grpc.CallOption) (*GetLostFoundListResponse, error) {
	client := lostfound.NewLostFoundServiceClient(m.cli.Conn())
	return client.GetLostFoundList(ctx, in, opts...)
}

// 获取失物招领详情
func (m *defaultLostFoundService) GetLostFoundDetail(ctx context.Context, in *GetLostFoundDetailRequest, opts ...grpc.CallOption) (*GetLostFoundDetailResponse, error) {
	client := lostfound.NewLostFoundServiceClient(m.cli.Conn())
	return client.GetLostFoundDetail(ctx, in, opts...)
}

// 获取用户发布的失物招领
func (m *defaultLostFoundService) GetUserLostFound(ctx context.Context, in *GetUserLostFoundRequest, opts ...grpc.CallOption) (*GetUserLostFoundResponse, error) {
	client := lostfound.NewLostFoundServiceClient(m.cli.Conn())
	return client.GetUserLostFound(ctx, in, opts...)
}

// 发布失物招领
func (m *defaultLostFoundService) PublishLostFound(ctx context.Context, in *PublishLostFoundRequest, opts ...grpc.CallOption) (*PublishLostFoundResponse, error) {
	client := lostfound.NewLostFoundServiceClient(m.cli.Conn())
	return client.PublishLostFound(ctx, in, opts...)
}

// 更新失物招领
func (m *defaultLostFoundService) UpdateLostFound(ctx context.Context, in *UpdateLostFoundRequest, opts ...grpc.CallOption) (*UpdateLostFoundResponse, error) {
	client := lostfound.NewLostFoundServiceClient(m.cli.Conn())
	return client.UpdateLostFound(ctx, in, opts...)
}

// 删除失物招领
func (m *defaultLostFoundService) DeleteLostFound(ctx context.Context, in *DeleteLostFoundRequest, opts ...grpc.CallOption) (*DeleteLostFoundResponse, error) {
	client := lostfound.NewLostFoundServiceClient(m.cli.Conn())
	return client.DeleteLostFound(ctx, in, opts...)
}

// 更新失物招领状态
func (m *defaultLostFoundService) UpdateLostFoundStatus(ctx context.Context, in *UpdateLostFoundStatusRequest, opts ...grpc.CallOption) (*UpdateLostFoundStatusResponse, error) {
	client := lostfound.NewLostFoundServiceClient(m.cli.Conn())
	return client.UpdateLostFoundStatus(ctx, in, opts...)
}

// 评论失物招领
func (m *defaultLostFoundService) CommentLostFound(ctx context.Context, in *CommentLostFoundRequest, opts ...grpc.CallOption) (*CommentLostFoundResponse, error) {
	client := lostfound.NewLostFoundServiceClient(m.cli.Conn())
	return client.CommentLostFound(ctx, in, opts...)
}

// 获取失物招领评论
func (m *defaultLostFoundService) GetLostFoundComments(ctx context.Context, in *GetLostFoundCommentsRequest, opts ...grpc.CallOption) (*GetLostFoundCommentsResponse, error) {
	client := lostfound.NewLostFoundServiceClient(m.cli.Conn())
	return client.GetLostFoundComments(ctx, in, opts...)
}

// 点赞失物招领
func (m *defaultLostFoundService) LikeLostFound(ctx context.Context, in *LikeLostFoundRequest, opts ...grpc.CallOption) (*LikeLostFoundResponse, error) {
	client := lostfound.NewLostFoundServiceClient(m.cli.Conn())
	return client.LikeLostFound(ctx, in, opts...)
}

// 取消点赞失物招领
func (m *defaultLostFoundService) UnlikeLostFound(ctx context.Context, in *UnlikeLostFoundRequest, opts ...grpc.CallOption) (*UnlikeLostFoundResponse, error) {
	client := lostfound.NewLostFoundServiceClient(m.cli.Conn())
	return client.UnlikeLostFound(ctx, in, opts...)
}
