// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	categoryFieldNames          = builder.RawFieldNames(&Category{})
	categoryRows                = strings.Join(categoryFieldNames, ",")
	categoryRowsExpectAutoSet   = strings.Join(stringx.Remove(categoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	categoryRowsWithPlaceHolder = strings.Join(stringx.Remove(categoryFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGoappCategoryIdPrefix = "cache:goapp:category:id:"
)

type (
	categoryModel interface {
		Insert(ctx context.Context, data *Category) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Category, error)
		Update(ctx context.Context, data *Category) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultCategoryModel struct {
		sqlc.CachedConn
		table string
	}

	Category struct {
		Id          uint64         `db:"id"`          // 分类ID
		Name        string         `db:"name"`        // 分类名称
		Icon        sql.NullString `db:"icon"`        // 分类图标URL
		ParentId    uint64         `db:"parent_id"`   // 父分类ID，0 表示顶级分类
		Level       uint64         `db:"level"`       // 分类层级
		Sort        uint64         `db:"sort"`        // 排序值，越大越靠前
		Description sql.NullString `db:"description"` // 分类描述
	}
)

func newCategoryModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultCategoryModel {
	return &defaultCategoryModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`category`",
	}
}

func (m *defaultCategoryModel) Delete(ctx context.Context, id uint64) error {
	goappCategoryIdKey := fmt.Sprintf("%s%v", cacheGoappCategoryIdPrefix, id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, goappCategoryIdKey)
	return err
}

func (m *defaultCategoryModel) FindOne(ctx context.Context, id uint64) (*Category, error) {
	goappCategoryIdKey := fmt.Sprintf("%s%v", cacheGoappCategoryIdPrefix, id)
	var resp Category
	err := m.QueryRowCtx(ctx, &resp, goappCategoryIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", categoryRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCategoryModel) Insert(ctx context.Context, data *Category) (sql.Result, error) {
	goappCategoryIdKey := fmt.Sprintf("%s%v", cacheGoappCategoryIdPrefix, data.Id)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, categoryRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.Name, data.Icon, data.ParentId, data.Level, data.Sort, data.Description)
	}, goappCategoryIdKey)
	return ret, err
}

func (m *defaultCategoryModel) Update(ctx context.Context, data *Category) error {
	goappCategoryIdKey := fmt.Sprintf("%s%v", cacheGoappCategoryIdPrefix, data.Id)
	_, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, categoryRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, data.Name, data.Icon, data.ParentId, data.Level, data.Sort, data.Description, data.Id)
	}, goappCategoryIdKey)
	return err
}

func (m *defaultCategoryModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGoappCategoryIdPrefix, primary)
}

func (m *defaultCategoryModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", categoryRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultCategoryModel) tableName() string {
	return m.table
}
