// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.8.1

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	favoriteFieldNames          = builder.RawFieldNames(&Favorite{})
	favoriteRows                = strings.Join(favoriteFieldNames, ",")
	favoriteRowsExpectAutoSet   = strings.Join(stringx.Remove(favoriteFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	favoriteRowsWithPlaceHolder = strings.Join(stringx.Remove(favoriteFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGoappFavoriteIdPrefix              = "cache:goapp:favorite:id:"
	cacheGoappFavoriteUserIdProductIdPrefix = "cache:goapp:favorite:userId:productId:"
)

type (
	favoriteModel interface {
		Insert(ctx context.Context, data *Favorite) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*Favorite, error)
		FindOneByUserIdProductId(ctx context.Context, userId uint64, productId uint64) (*Favorite, error)
		Update(ctx context.Context, data *Favorite) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultFavoriteModel struct {
		sqlc.CachedConn
		table string
	}

	Favorite struct {
		Id        uint64    `db:"id"`         // 主键，收藏ID
		UserId    uint64    `db:"user_id"`    // 用户ID
		ProductId uint64    `db:"product_id"` // 商品ID
		CreatedAt time.Time `db:"created_at"` // 收藏时间
	}
)

func newFavoriteModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultFavoriteModel {
	return &defaultFavoriteModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`favorite`",
	}
}

func (m *defaultFavoriteModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	goappFavoriteIdKey := fmt.Sprintf("%s%v", cacheGoappFavoriteIdPrefix, id)
	goappFavoriteUserIdProductIdKey := fmt.Sprintf("%s%v:%v", cacheGoappFavoriteUserIdProductIdPrefix, data.UserId, data.ProductId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, goappFavoriteIdKey, goappFavoriteUserIdProductIdKey)
	return err
}

func (m *defaultFavoriteModel) FindOne(ctx context.Context, id uint64) (*Favorite, error) {
	goappFavoriteIdKey := fmt.Sprintf("%s%v", cacheGoappFavoriteIdPrefix, id)
	var resp Favorite
	err := m.QueryRowCtx(ctx, &resp, goappFavoriteIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", favoriteRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFavoriteModel) FindOneByUserIdProductId(ctx context.Context, userId uint64, productId uint64) (*Favorite, error) {
	goappFavoriteUserIdProductIdKey := fmt.Sprintf("%s%v:%v", cacheGoappFavoriteUserIdProductIdPrefix, userId, productId)
	var resp Favorite
	err := m.QueryRowIndexCtx(ctx, &resp, goappFavoriteUserIdProductIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `product_id` = ? limit 1", favoriteRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, productId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFavoriteModel) Insert(ctx context.Context, data *Favorite) (sql.Result, error) {
	goappFavoriteIdKey := fmt.Sprintf("%s%v", cacheGoappFavoriteIdPrefix, data.Id)
	goappFavoriteUserIdProductIdKey := fmt.Sprintf("%s%v:%v", cacheGoappFavoriteUserIdProductIdPrefix, data.UserId, data.ProductId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, favoriteRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.ProductId)
	}, goappFavoriteIdKey, goappFavoriteUserIdProductIdKey)
	return ret, err
}

func (m *defaultFavoriteModel) Update(ctx context.Context, newData *Favorite) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	goappFavoriteIdKey := fmt.Sprintf("%s%v", cacheGoappFavoriteIdPrefix, data.Id)
	goappFavoriteUserIdProductIdKey := fmt.Sprintf("%s%v:%v", cacheGoappFavoriteUserIdProductIdPrefix, data.UserId, data.ProductId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, favoriteRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.ProductId, newData.Id)
	}, goappFavoriteIdKey, goappFavoriteUserIdProductIdKey)
	return err
}

func (m *defaultFavoriteModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGoappFavoriteIdPrefix, primary)
}

func (m *defaultFavoriteModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", favoriteRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultFavoriteModel) tableName() string {
	return m.table
}
