CREATE TABLE `lost_found_item` (
       `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '失物招领记录ID',
       `title` VARCHAR(255) NOT NULL COMMENT '标题',
       `description` TEXT NOT NULL COMMENT '详细描述',
       `type` ENUM('lost', 'found') NOT NULL COMMENT '类型：lost（丢失） 或 found（招领）',
       `category` VARCHAR(100) DEFAULT NULL COMMENT '分类，若有预定义分类可考虑独立表',
       `location` VARCHAR(255) DEFAULT NULL COMMENT '大致位置信息，如校区或城市',
       `location_detail` JSON DEFAULT NULL COMMENT '详细位置信息（例如：经纬度、具体地址）',
       `contact_info` VARCHAR(255) DEFAULT NULL COMMENT '联系信息',
       `contact_way` VARCHAR(100) DEFAULT NULL COMMENT '联系方式，例如电话、微信等',
       `images` JSON DEFAULT NULL COMMENT '图片列表，JSON 数组格式',
       `status` ENUM('pending','found','claimed','closed') NOT NULL DEFAULT 'pending' COMMENT '状态：待处理、已找到、已认领、已关闭',
       `tags` JSON DEFAULT NULL COMMENT '标签列表，JSON 数组格式',
       `reward_info` VARCHAR(255) DEFAULT NULL COMMENT '悬赏信息',
       `lost_found_time` DATETIME DEFAULT NULL COMMENT '丢失或拾取时间',
       `publisher_id` BIGINT UNSIGNED NOT NULL COMMENT '发布者ID，关联用户表',
       `publisher_name` VARCHAR(100) NOT NULL COMMENT '发布者名称（冗余字段，方便展示）',
       `publisher_avatar` VARCHAR(255) DEFAULT NULL COMMENT '发布者头像URL（冗余字段）',
       `view_count` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '浏览数',
       `like_count` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '点赞数',
       `comment_count` BIGINT UNSIGNED NOT NULL DEFAULT 0 COMMENT '评论数',
       `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
       `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
       PRIMARY KEY (`id`),
       KEY `idx_publisher_id` (`publisher_id`),
       KEY `idx_type` (`type`),
       KEY `idx_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='失物招领记录表';
